[pytest]
markers =
    asyncio: mark test as async using asyncio
    anyio: mark test as async using anyio
filterwarnings =
    ignore::pytest.PytestConfigWarning
    ignore::pytest.PytestUnknownMarkWarning
    ignore::DeprecationWarning
    ignore::UserWarning
