# app/prompts package

from .agent_prompts import (
    AGENT_BASE_PROMPT,
    AGENT_SUMMARY_PROMPT,
    AGENT_SUMMARY_PERSONA,
    AGENT_FINAL_TURN_PROMPT,
)
from .summarization_prompts import (
    RESEARCH_INTELLIGENCE_SYSTEM_PROMPT,
    PAPER_COMMUNICATOR_PROMPT_TEMPLATE,
    PRESENTATION_PRESENTER_PROMPT_TEMPLATE,
)
from .prediction_prompts import PREDICTION_SYSTEM_PROMPT
from .scraping_prompts import JSON_PARSER_SYSTEM_PROMPT
from .pipeline_prompts import (
    DAILY_FEED_ADVISOR_PROMPT_TEMPLATE,
    METADATA_EXTRACTION_PROMPT_TEMPLATE,
    AUTHOR_CHAT_SYSTEM_PROMPT_TEMPLATE,
    GRANT_ADVISOR_PROMPT_TEMPLATE,
    SYNERGY_COUNSELOR_PROMPT_TEMPLATE,
    JOURNAL_ADVISOR_RATIONALE_PROMPT_TEMPLATE,
)
from .quest_prompts import QUESTS_GENERATION_PROMPT_TEMPLATE

__all__ = [
    "AGENT_BASE_PROMPT",
    "AGENT_SUMMARY_PROMPT",
    "AGENT_SUMMARY_PERSONA",
    "AGENT_FINAL_TURN_PROMPT",
    "RESEARCH_INTELLIGENCE_SYSTEM_PROMPT",
    "PAPER_COMMUNICATOR_PROMPT_TEMPLATE",
    "PRESENTATION_PRESENTER_PROMPT_TEMPLATE",
    "PREDICTION_SYSTEM_PROMPT",
    "JSON_PARSER_SYSTEM_PROMPT",
    "DAILY_FEED_ADVISOR_PROMPT_TEMPLATE",
    "METADATA_EXTRACTION_PROMPT_TEMPLATE",
    "AUTHOR_CHAT_SYSTEM_PROMPT_TEMPLATE",
    "GRANT_ADVISOR_PROMPT_TEMPLATE",
    "SYNERGY_COUNSELOR_PROMPT_TEMPLATE",
    "JOURNAL_ADVISOR_RATIONALE_PROMPT_TEMPLATE",
    "QUESTS_GENERATION_PROMPT_TEMPLATE",
]
