version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: skolab_prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alertmanager-alerts.yml:/etc/prometheus/alertmanager-alerts.yml
    ports:
      - "9090:9090"
    depends_on:
      - alertmanager

  alertmanager:
    image: prom/alertmanager:latest
    container_name: skolab_alertmanager
    restart: always
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"

  grafana:
    image: grafana/grafana:latest
    container_name: skolab_grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:2.9.0
    container_name: skolab_loki
    restart: always
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.0
    container_name: skolab_promtail
    restart: always
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki
