"""Initial schema

Revision ID: 631e4c40102e
Revises:
Create Date: 2026-06-04 00:24:40.074469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "631e4c40102e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_adu_user"), table_name="agent_document_uploads")
    op.create_index(
        op.f("ix_agent_document_uploads_user_id"),
        "agent_document_uploads",
        ["user_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("agent_history_summaries_cache_key_key"),
        "agent_history_summaries",
        type_="unique",
    )
    op.drop_index(op.f("ix_ahs_key"), table_name="agent_history_summaries")
    op.drop_index(op.f("ix_ahs_user"), table_name="agent_history_summaries")
    op.create_index(
        op.f("ix_agent_history_summaries_cache_key"),
        "agent_history_summaries",
        ["cache_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_agent_history_summaries_user_id"),
        "agent_history_summaries",
        ["user_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_arl_created"), table_name="api_request_log")
    op.drop_index(op.f("ix_arl_endpoint"), table_name="api_request_log")
    op.create_index(
        op.f("ix_api_request_log_created_at"),
        "api_request_log",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_request_log_endpoint"),
        "api_request_log",
        ["endpoint"],
        unique=False,
    )
    op.drop_constraint(
        op.f("author_search_log_openalex_id_key"), "author_search_log", type_="unique"
    )
    op.create_index(
        op.f("ix_author_search_log_openalex_id"),
        "author_search_log",
        ["openalex_id"],
        unique=False,
    )
    op.alter_column(
        "conjectures",
        "options",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_conjectures_author"), table_name="conjectures")
    op.create_index(
        op.f("ix_conjectures_author_openalex_id"),
        "conjectures",
        ["author_openalex_id"],
        unique=False,
    )
    op.alter_column(
        "daily_feed_items",
        "concepts",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "daily_feed_items",
        "authors",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "daily_feed_items",
        "raw_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_dfi_author"), table_name="daily_feed_items")
    op.create_index(
        op.f("ix_daily_feed_items_author_openalex_id"),
        "daily_feed_items",
        ["author_openalex_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_rc_author"), table_name="researcher_connections")
    op.drop_index(op.f("ix_rc_connection"), table_name="researcher_connections")
    op.create_index(
        op.f("ix_researcher_connections_author_openalex_id"),
        "researcher_connections",
        ["author_openalex_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_researcher_connections_connection_openalex_id"),
        "researcher_connections",
        ["connection_openalex_id"],
        unique=False,
    )
    op.alter_column(
        "researcher_metrics",
        "expertise",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "researcher_metrics",
        "academic_history",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_researcher_metrics_id"), table_name="researcher_metrics")
    op.create_index(
        op.f("ix_researcher_metrics_openalex_id"),
        "researcher_metrics",
        ["openalex_id"],
        unique=False,
    )
    op.alter_column(
        "researcher_profiles",
        "concepts",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "researcher_profiles",
        "raw_profile",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_rp_openalex"), table_name="researcher_profiles")
    op.create_index(
        op.f("ix_researcher_profiles_openalex_id"),
        "researcher_profiles",
        ["openalex_id"],
        unique=False,
    )
    op.alter_column(
        "researcher_works",
        "concepts",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "researcher_works",
        "countries",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_rw_author"), table_name="researcher_works")
    op.drop_index(op.f("ix_rw_work"), table_name="researcher_works")
    op.create_index(
        op.f("ix_researcher_works_author_openalex_id"),
        "researcher_works",
        ["author_openalex_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_researcher_works_work_openalex_id"),
        "researcher_works",
        ["work_openalex_id"],
        unique=False,
    )
    op.alter_column(
        "user_activity_log",
        "event_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_ual_created"), table_name="user_activity_log")
    op.create_index(
        op.f("ix_user_activity_log_created_at"),
        "user_activity_log",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_activity_log_event_type"),
        "user_activity_log",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_activity_log_user_id"),
        "user_activity_log",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "user_settings",
        "feed_topics",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "user_settings",
        "preferred_journals",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "user_settings",
        "preferred_fields",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_user_settings_uid"), table_name="user_settings")
    op.create_index(
        op.f("ix_user_settings_user_id"), "user_settings", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_settings_user_id"), table_name="user_settings")
    op.create_index(
        op.f("ix_user_settings_uid"), "user_settings", ["user_id"], unique=False
    )
    op.alter_column(
        "user_settings",
        "preferred_fields",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "user_settings",
        "preferred_journals",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "user_settings",
        "feed_topics",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_user_activity_log_user_id"), table_name="user_activity_log")
    op.drop_index(
        op.f("ix_user_activity_log_event_type"), table_name="user_activity_log"
    )
    op.drop_index(
        op.f("ix_user_activity_log_created_at"), table_name="user_activity_log"
    )
    op.create_index(
        op.f("ix_ual_created"), "user_activity_log", ["created_at"], unique=False
    )
    op.alter_column(
        "user_activity_log",
        "event_metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_researcher_works_work_openalex_id"), table_name="researcher_works"
    )
    op.drop_index(
        op.f("ix_researcher_works_author_openalex_id"), table_name="researcher_works"
    )
    op.create_index(
        op.f("ix_rw_work"), "researcher_works", ["work_openalex_id"], unique=False
    )
    op.create_index(
        op.f("ix_rw_author"), "researcher_works", ["author_openalex_id"], unique=False
    )
    op.alter_column(
        "researcher_works",
        "countries",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "researcher_works",
        "concepts",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_researcher_profiles_openalex_id"), table_name="researcher_profiles"
    )
    op.create_index(
        op.f("ix_rp_openalex"), "researcher_profiles", ["openalex_id"], unique=False
    )
    op.alter_column(
        "researcher_profiles",
        "raw_profile",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "researcher_profiles",
        "concepts",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_researcher_metrics_openalex_id"), table_name="researcher_metrics"
    )
    op.create_index(
        op.f("ix_researcher_metrics_id"),
        "researcher_metrics",
        ["openalex_id"],
        unique=False,
    )
    op.alter_column(
        "researcher_metrics",
        "academic_history",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "researcher_metrics",
        "expertise",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_researcher_connections_connection_openalex_id"),
        table_name="researcher_connections",
    )
    op.drop_index(
        op.f("ix_researcher_connections_author_openalex_id"),
        table_name="researcher_connections",
    )
    op.create_index(
        op.f("ix_rc_connection"),
        "researcher_connections",
        ["connection_openalex_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rc_author"),
        "researcher_connections",
        ["author_openalex_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_daily_feed_items_author_openalex_id"), table_name="daily_feed_items"
    )
    op.create_index(
        op.f("ix_dfi_author"), "daily_feed_items", ["author_openalex_id"], unique=False
    )
    op.alter_column(
        "daily_feed_items",
        "raw_data",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "daily_feed_items",
        "authors",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "daily_feed_items",
        "concepts",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_conjectures_author_openalex_id"), table_name="conjectures")
    op.create_index(
        op.f("ix_conjectures_author"),
        "conjectures",
        ["author_openalex_id"],
        unique=False,
    )
    op.alter_column(
        "conjectures",
        "options",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_author_search_log_openalex_id"), table_name="author_search_log"
    )
    op.create_unique_constraint(
        op.f("author_search_log_openalex_id_key"),
        "author_search_log",
        ["openalex_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_api_request_log_endpoint"), table_name="api_request_log")
    op.drop_index(op.f("ix_api_request_log_created_at"), table_name="api_request_log")
    op.create_index(
        op.f("ix_arl_endpoint"), "api_request_log", ["endpoint"], unique=False
    )
    op.create_index(
        op.f("ix_arl_created"), "api_request_log", ["created_at"], unique=False
    )
    op.drop_index(
        op.f("ix_agent_history_summaries_user_id"), table_name="agent_history_summaries"
    )
    op.drop_index(
        op.f("ix_agent_history_summaries_cache_key"),
        table_name="agent_history_summaries",
    )
    op.create_index(
        op.f("ix_ahs_user"), "agent_history_summaries", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_ahs_key"), "agent_history_summaries", ["cache_key"], unique=False
    )
    op.create_unique_constraint(
        op.f("agent_history_summaries_cache_key_key"),
        "agent_history_summaries",
        ["cache_key"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(
        op.f("ix_agent_document_uploads_user_id"), table_name="agent_document_uploads"
    )
    op.create_index(
        op.f("ix_adu_user"), "agent_document_uploads", ["user_id"], unique=False
    )
    # ### end Alembic commands ###
