"""Initial schema

Revision ID: 631e4c40102e
Revises:
Create Date: 2026-06-04 00:24:40.074469

Originally autogenerated as a *reconcile* migration: it assumed every table
already existed (built by ``Base.metadata.create_all`` in an even earlier
bootstrap) and only renamed legacy indexes to Alembic conventions, swapped a
few unique constraints for indexes, and converted JSONB columns to JSON. Run
against a clean database it died on the first ``DROP INDEX`` because the table
did not exist yet (2026-09 incident).

Rewritten to be a real from-scratch bootstrap **and** idempotent:

1. ``Base.metadata.create_all`` first — creates every table on a fresh DB, a
   no-op on one that already has them.
2. Every reconcile step is now ``IF EXISTS`` / ``IF NOT EXISTS`` (and
   Postgres-only steps are dialect-guarded), so this revision applies cleanly
   whether the DB is empty, was built by ``create_all``, or is a half-migrated
   legacy instance.
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "631e4c40102e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ── helpers ────────────────────────────────────────────────────────────────
def _is_pg() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def _exec(sql: str) -> None:
    """Run one best-effort DDL statement; a failure is logged, never fatal."""
    try:
        op.execute(sql)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            f"[migration 631e4c40102e] skipped: {sql.strip()[:80]} — {exc}", flush=True
        )


def _drop_index(name: str) -> None:
    _exec(f"DROP INDEX IF EXISTS {name}")


def _create_index(name: str, table: str, cols: str, *, unique: bool = False) -> None:
    kind = "UNIQUE INDEX" if unique else "INDEX"
    _exec(f"CREATE {kind} IF NOT EXISTS {name} ON {table} ({cols})")


def _drop_constraint(table: str, name: str) -> None:
    if _is_pg():
        _exec(f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {name}")


def _jsonb_to_json(table: str, col: str) -> None:
    # Only meaningful on a legacy DB whose column is still JSONB; on a DB that
    # create_all just built the column is already JSON and this is a no-op.
    if _is_pg():
        _exec(f'ALTER TABLE {table} ALTER COLUMN "{col}" TYPE json USING "{col}"::json')


def _create_all() -> None:
    from app.db.database import Base

    import app.models.user_models  # noqa: F401
    import app.models.researcher_models  # noqa: F401
    import app.models.agent_models  # noqa: F401
    import app.models.analytics_models  # noqa: F401
    import app.models.content_models  # noqa: F401

    Base.metadata.create_all(bind=op.get_bind())


# ── upgrade ────────────────────────────────────────────────────────────────
def upgrade() -> None:
    # 1. Every table exists after this — fresh DB gets them, existing DB no-op.
    _create_all()

    # 2. Reconcile legacy index / constraint names and JSONB→JSON. Each step is
    #    idempotent, so this is safe on a DB create_all just built too.
    _drop_index("ix_adu_user")
    _create_index(
        "ix_agent_document_uploads_user_id", "agent_document_uploads", "user_id"
    )

    _drop_constraint("agent_history_summaries", "agent_history_summaries_cache_key_key")
    _drop_index("ix_ahs_key")
    _drop_index("ix_ahs_user")
    _create_index(
        "ix_agent_history_summaries_cache_key",
        "agent_history_summaries",
        "cache_key",
        unique=True,
    )
    _create_index(
        "ix_agent_history_summaries_user_id", "agent_history_summaries", "user_id"
    )

    _drop_index("ix_arl_created")
    _drop_index("ix_arl_endpoint")
    _create_index("ix_api_request_log_created_at", "api_request_log", "created_at")
    _create_index("ix_api_request_log_endpoint", "api_request_log", "endpoint")

    _drop_constraint("author_search_log", "author_search_log_openalex_id_key")
    _create_index(
        "ix_author_search_log_openalex_id", "author_search_log", "openalex_id"
    )

    _jsonb_to_json("conjectures", "options")
    _drop_index("ix_conjectures_author")
    _create_index(
        "ix_conjectures_author_openalex_id", "conjectures", "author_openalex_id"
    )

    _jsonb_to_json("daily_feed_items", "concepts")
    _jsonb_to_json("daily_feed_items", "authors")
    _jsonb_to_json("daily_feed_items", "raw_data")
    _drop_index("ix_dfi_author")
    _create_index(
        "ix_daily_feed_items_author_openalex_id",
        "daily_feed_items",
        "author_openalex_id",
    )

    _drop_index("ix_rc_author")
    _drop_index("ix_rc_connection")
    _create_index(
        "ix_researcher_connections_author_openalex_id",
        "researcher_connections",
        "author_openalex_id",
    )
    _create_index(
        "ix_researcher_connections_connection_openalex_id",
        "researcher_connections",
        "connection_openalex_id",
    )

    _jsonb_to_json("researcher_metrics", "expertise")
    _jsonb_to_json("researcher_metrics", "academic_history")
    _drop_index("ix_researcher_metrics_id")
    _create_index(
        "ix_researcher_metrics_openalex_id", "researcher_metrics", "openalex_id"
    )

    _jsonb_to_json("researcher_profiles", "concepts")
    _jsonb_to_json("researcher_profiles", "raw_profile")
    _drop_index("ix_rp_openalex")
    _create_index(
        "ix_researcher_profiles_openalex_id", "researcher_profiles", "openalex_id"
    )

    _jsonb_to_json("researcher_works", "concepts")
    _jsonb_to_json("researcher_works", "countries")
    _drop_index("ix_rw_author")
    _drop_index("ix_rw_work")
    _create_index(
        "ix_researcher_works_author_openalex_id",
        "researcher_works",
        "author_openalex_id",
    )
    _create_index(
        "ix_researcher_works_work_openalex_id",
        "researcher_works",
        "work_openalex_id",
    )

    _jsonb_to_json("user_activity_log", "event_metadata")
    _drop_index("ix_ual_created")
    _create_index("ix_user_activity_log_created_at", "user_activity_log", "created_at")
    _create_index("ix_user_activity_log_event_type", "user_activity_log", "event_type")
    _create_index("ix_user_activity_log_user_id", "user_activity_log", "user_id")

    _jsonb_to_json("user_settings", "feed_topics")
    _jsonb_to_json("user_settings", "preferred_journals")
    _jsonb_to_json("user_settings", "preferred_fields")
    _drop_index("ix_user_settings_uid")
    _create_index("ix_user_settings_user_id", "user_settings", "user_id")


# ── downgrade ──────────────────────────────────────────────────────────────
def downgrade() -> None:
    """Best-effort reverse of the reconcile step (index names only).

    Does NOT drop tables — "downgrade past the initial revision" means an empty
    database, which is better done by dropping the schema directly than by a
    migration.
    """
    _drop_index("ix_user_settings_user_id")
    _create_index("ix_user_settings_uid", "user_settings", "user_id")

    _drop_index("ix_user_activity_log_user_id")
    _drop_index("ix_user_activity_log_event_type")
    _drop_index("ix_user_activity_log_created_at")
    _create_index("ix_ual_created", "user_activity_log", "created_at")

    _drop_index("ix_researcher_works_work_openalex_id")
    _drop_index("ix_researcher_works_author_openalex_id")
    _create_index("ix_rw_work", "researcher_works", "work_openalex_id")
    _create_index("ix_rw_author", "researcher_works", "author_openalex_id")

    _drop_index("ix_researcher_profiles_openalex_id")
    _create_index("ix_rp_openalex", "researcher_profiles", "openalex_id")

    _drop_index("ix_researcher_metrics_openalex_id")
    _create_index("ix_researcher_metrics_id", "researcher_metrics", "openalex_id")

    _drop_index("ix_researcher_connections_connection_openalex_id")
    _drop_index("ix_researcher_connections_author_openalex_id")
    _create_index(
        "ix_rc_connection", "researcher_connections", "connection_openalex_id"
    )
    _create_index("ix_rc_author", "researcher_connections", "author_openalex_id")

    _drop_index("ix_daily_feed_items_author_openalex_id")
    _create_index("ix_dfi_author", "daily_feed_items", "author_openalex_id")

    _drop_index("ix_conjectures_author_openalex_id")
    _create_index("ix_conjectures_author", "conjectures", "author_openalex_id")

    _drop_index("ix_author_search_log_openalex_id")
    if _is_pg():
        _exec(
            "ALTER TABLE author_search_log ADD CONSTRAINT "
            "author_search_log_openalex_id_key UNIQUE (openalex_id)"
        )

    _drop_index("ix_api_request_log_endpoint")
    _drop_index("ix_api_request_log_created_at")
    _create_index("ix_arl_endpoint", "api_request_log", "endpoint")
    _create_index("ix_arl_created", "api_request_log", "created_at")

    _drop_index("ix_agent_history_summaries_user_id")
    _drop_index("ix_agent_history_summaries_cache_key")
    _create_index("ix_ahs_user", "agent_history_summaries", "user_id")
    _create_index("ix_ahs_key", "agent_history_summaries", "cache_key")
    if _is_pg():
        _exec(
            "ALTER TABLE agent_history_summaries ADD CONSTRAINT "
            "agent_history_summaries_cache_key_key UNIQUE (cache_key)"
        )

    _drop_index("ix_agent_document_uploads_user_id")
    _create_index("ix_adu_user", "agent_document_uploads", "user_id")
